spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/catalinaLi/config_repo
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.136.128
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764 #\u5BA2\u6237\u7AEF\u7AEF\u53E3
management:
  endpoints:
    web:
      exposure:
        include: "*"