spring:
  application:
    name: eureka #\u5E94\u7528\u7684\u540D\u79F0
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # \u901A\u8FC7\u6DFB\u52A0\u914D\u7F6E\u6211\u4EEC\u8FD9\u91CC\u5FFD\u7565\u81EA\u5DF1
    register-with-eureka: false #\u8868\u793A\u662F\u5426\u6CE8\u518C\u81EA\u8EAB\u5230eureka\u670D\u52A1\u5668
    fetch-registry: false #\u8868\u793A\u662F\u5426\u4ECEeureka\u670D\u52A1\u5668\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F